### ISSUE TITLE
Typo in test fnc name

### ISSUE THREAD

**Issue by cjharries-nexient** [nexient-llc/tf-module-skeleton#11]
https://github.com/nexient-llc/tf-module-skeleton/blob/feede5b1507d8edabf789a2cf5582022d0a29fba/tests/post_deploy_functional/random_with_cake_example_test.go#L34

This method is `TearDownSuite`

**Comment by lodenrogue** [comment]
PR: https://github.com/nexient-llc/tf-module-skeleton/pull/12

**Comment by cjharries-nexient** [comment]
Resolved!
