### ISSUE TITLE
Remove terraform_validate as on a commit it actively blocks commits

### ISSUE THREAD

**Issue by wright-nexient** [nexient-llc/tf-module-skeleton#18]
This is an unnecessary and blocking pre-commit plugin. Remove in `.pre-commit-config.yaml`

**Comment by wright-nexient** [comment]
This precommit plugin is a known issue. It's nice in _theory_ but this check is known to be broken.

**Comment by res0nat0r** [comment]
This will be fixed here: https://github.com/nexient-llc/tf-module-skeleton/pull/20

**Comment by wright-nexient** [comment]
Fixed in PR#20
