### ISSUE TITLE
Current TF pre-commit hook needs to be replaced

### ISSUE THREAD

**Issue by cjharries-nexient** [nexient-llc/tf-module-skeleton#19]
<img width="694" alt="Screen Shot 2022-08-05 at 1 25 34 PM" src="https://user-images.githubusercontent.com/97557000/183138777-ff2a7e2e-8fc2-44a0-ae6f-dcab80d5b2fd.png">

**Comment by cjharries-nexient** [comment]
The old hook seems to have broken and I'm not sure why

**Comment by res0nat0r** [comment]
This will be fixed here: https://github.com/nexient-llc/tf-module-skeleton/pull/20
